import { ReactNode } from "react"
import "@app/styles/globals.css"

import type { Metadata } from "next"
import { Inter } from "next/font/google"

import { QueryClientProvider } from "@app/components/reactQuery/QueryClientProvider"
import { ModeToggle } from "@app/components/theme/modeToggle"
import { ThemeProvider } from "@app/components/theme/themeProvider"
import { Box } from "@app/components/ui/box"
import { Row } from "@app/components/ui/row"
import { Toaster } from "@app/components/ui/toaster"
import { cn } from "@app/utils/shadcn/shadcnHelpers"
import { getLocale } from "next-intl/server"
import { NextIntlClientProvider } from "next-intl"

const interFont = Inter({
	subsets: ["latin"],
	variable: "--font-sans",
})

export const metadata: Metadata = {
	description: "Generated by create next app",
	title: "Create Next App",
}

type RootLayoutProps = { children: ReactNode }

export default async function RootLayout({ children }: RootLayoutProps) {
	const locale = await getLocale()

	console.log(locale)

	return (
		<html lang={locale}>
			<body className={cn("min-h-screen bg-background font-sans antialiased", interFont.variable)}>
				<NextIntlClientProvider>
					<ThemeProvider disableTransitionOnChange enableSystem attribute="class" defaultTheme="dark">
						<QueryClientProvider>
							<Box className="p-5 h-screen">
								<Row className="absolute top-5 right-5">
									<ModeToggle />
								</Row>

								{children}
							</Box>

							<Toaster />
						</QueryClientProvider>
					</ThemeProvider>
				</NextIntlClientProvider>
			</body>
		</html>
	)
}
