import { ReactNode } from "react"
import "services/words/src/styles/globals.css"

import type { Metadata } from "next"
import { Geist_Mono } from "next/font/google"

import { QueryClientProvider } from "services/words/src/components/reactQuery/QueryClientProvider"
import { Box } from "services/words/src/components/ui/box"
import { Row } from "services/words/src/components/ui/row"
import { Toaster } from "services/words/src/components/ui/toaster"
import { cn } from "services/words/src/utils/shadcn/shadcnHelpers"
import { getLocale } from "next-intl/server"
import { NextIntlClientProvider } from "next-intl"

const font = Geist_Mono({
	subsets: ["latin"],
	variable: "--font-sans",
})

export const metadata: Metadata = {
	description: "Generated by create next app",
	title: "Create Next App",
}

type RootLayoutProps = { children: ReactNode }

export default async function RootLayout({ children }: RootLayoutProps) {
	const locale = await getLocale()

	return (
		<html lang={locale}>
			<body className={cn("min-h-screen bg-background font-sans antialiased", font.variable)}>
				<NextIntlClientProvider>
					<QueryClientProvider>
						<Box className="p-5 h-screen">{children}</Box>
						<Toaster />
					</QueryClientProvider>
				</NextIntlClientProvider>
			</body>
		</html>
	)
}
